config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root :to => redirect('/login')
  
  resources :users, only: [:new, :create, :edit, :update, :show, :destroy]
  resources :departments, only:[:new, :create, :show] do
    resources :shifts
  end
  resources :employees

  get '/login', to: 'sessions#login'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  put '/employees', to: 'employees#update'

  get '/departments', to: 'departments#index'


end

app/models/department.rb
class Department < ActiveRecord::Base
    has_many :shifts
    has_many :employees
    belongs_to :manager
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
    before_action :authorize
    before_action :can_enter?
    before_action :your_department?, only: [:show]
    skip_before_action :verify_authenticity_token
    @@date_value = Time.now.strftime("%d-%m-%Y")

    def new
        @department = Department.new
    end

    def create
        @@date_value = date_param unless date_param == ""
        redirect_to departments_path
    end

    def index
        @date_value = @@date_value
        @departments = Department.all
    end

    def show
        id = params[:id]
        # begin
        @date_value = @@date_value
        @department = Department.find(id)

        # rescue
        #     redirect_to departments_path
        # end
    end




    private

    def date_param
        params[:date]
    end

    def your_department?
        department = Department.find(params[:id])
        unless department.manager.user == current_user
            flash[:notice] = "This department doesn't belong to you."
            redirect_to departments_path
        end
    end
    

    
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/views/departments/_flash.html.erb
<% flash.each do |type, msg| %>
    <div class="alert alert-success" role="alert">
        <%= msg %>
    </div>
<% end %>

app/views/departments/index.html.erb
<!DOCTYPE html>
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"></script>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
    <%= render :partial => 'flash' %>
    <div class="container w-50">
        <div class="my-3 d-flex justify-content-center">
            <h1 class="text">Departments <span id='date'><%= @date_value %></span></h1>
            <h1 class="ml-3 align-self-center"><span id="datepicker"><i class="fa fa-calendar"></i></span></h1>
            <form id="send-date" action="/departments" method="post">
                <input type="hidden" class="form-control" name="date">
            </form>
        </div>
        <div class="row">
            <% @departments.each_with_index do |department, index| %>
                <div class="col-sm-6">
                    <div class = "card">
                        <div class="card-body">
                            <h5 class="card-title"><%= department.title %></h5>
                            <p class="card-text">Manager: <%= department.manager.name %><br>
                                Employee Amount: <%= department.employees.size %><br>
                                Shift Amount: <%= department.shifts.day_filter(Date.parse(@date_value)).size %>
                            </p>
                            <%= link_to '<button>details</button>'.html_safe,  department_path(department.id)%>
                        </div>
                    </div>
                </div>
            <% end %>
        </div>
    </div>                                           
</body>
</html>

app/views/departments/shift_detail.html.erb
<!DOCTYPE html>
<html>
<head>
</head>
<body>
    <div class="top">
        <a id="date"></a>
        <button class="actual">Actual</button>
        <button class="plan">Plan</button>
    </div>
    <div class="group">
        <table>
            <thead>
                <tr>
                    <th><input type="checkbox" id="select-all">Select All</th>
                    <th>Entry Time</th>
                    <th>Exit Time</th>
                    <th>Shift hours</th>
                    <th>Number of Employees</th>
                    <th>Manage</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td><input type="checkbox"></td>
                    <td>9.00</td>
                    <td>16.00</td>
                    <td>7</td>
                    <td>40</td>
                    <td>More info</td>
                </tr>
            </tbody>
        </table>
        <div class="content-right">
            <div class="add-worker">
                <table>
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Status</th>
                            <th>Work Time</th>
                            <th>Add</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>SomeOne Likeme</td>
                            <td>Free</td>
                            <td>0</td>
                            <td><button>Assign</button></td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="OT">
                <a>OT</a>
                <div class="manageOT">
                    <input type="text" placeholder="Hour" value="">
                    <br>
                    <button>Increase</button>
                    <button>Decrease</button>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

app/views/departments/show.html.erb
<!DOCTYPE html>
<html>
<head>
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
</head>
<body>
    <div class="container w-auto">
        <h3 class="my-4"><%= @department.title %> <span id='date'></span></h3>
        <div class="row">
            <table class="table table-striped table-bordered text-center">
                <thead>
                    <tr>
                        <th>Entry Time</th>
                        <th>Exit Time</th>
                        <th>Shift hours</th>
                        <th>Number of Employees</th>
                        <th>Manage</th>
                    </tr>
                </thead>
                <tbody>
                    <% @department.shifts.day_filter(Date.parse(@date_value)).each do |shift| %>
                        <tr>
                            <td><%= shift.check_in.localtime.strftime('%t%H:%M') %></td>
                            <td><%= shift.check_out.localtime.strftime('%t%H:%M') %></td>
                            <td><%= "%.2f" % [(shift.check_out - shift.check_in)/3600.0] %></td>
                            <td><%= shift.workplans.size %></td>
                            <td><%= link_to 'More info', department_shift_path(@department.id, shift.id) %></td>
                        </tr>
                    <% end %>
                </tbody>
                </table>
        </div>
    </div>
</body>
</html>