config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root :to => redirect('/login')
  
  resources :users, only: [:new, :create, :edit, :update, :show, :destroy]
  resources :departments, only:[:new, :create, :show] do
    resources :shifts
  end
  resources :employees

  get '/login', to: 'sessions#login'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  put '/employees', to: 'employees#update'

  get '/departments', to: 'departments#index'


end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CpfProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
  </head>
  <body>
    <nav class="navbar navbar-light bg-light">
      <div class="navbar-brand">
        <%= image_tag "CPF.png", height: 50 %>
        <% if is_manager?%>
          <%= link_to "Home", departments_path, class: "navbar-brand" %>
        <% elsif is_employee? %>
          My Shift
        <% end %>
      </div>
      <% if logged_in? %>
        <div class="d-flex">
          <a class="align-self-center mr-2"><i class="fa fa-user-circle-o" aria-hidden="true"></i> <%= current_user.username %></a>
          <%= link_to '<button class="btn btn-outline-success my-2 my-sm-0" type="submit">Logout</button>'.html_safe, '/logout', method: :get %>
        </div>
      <% end %>
    </nav>
    <%= yield %>
    <%= javascript_pack_tag 'date' %>
    <%= javascript_pack_tag 'select' %>
  </body>
</html>